"""name

Revision ID: 96f19b9271bd
Revises: edeb3f7c3733
Create Date: 2023-08-31 20:50:37.152095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f19b9271bd'
down_revision: Union[str, None] = 'edeb3f7c3733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stock_data', ['ticker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_data', type_='unique')
    # ### end Alembic commands ###
