USER_REGISTERED = "User Registered Successfully!"
USER_SIGN_IN_FAILED = "User Sign-In Failed, Try again."
USER_NOT_FOUND = "User not found, Try again."
DATA_ENTERED = "Stock has been Entered Successfully!"
DATA_NOT_FOUND = "Data not found, Try again."
TRANSACTION_ENTERED = "Transaction Completed Successfully!"